apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-app-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: wiz-app
    namespace: your-namespace
roleRef:
  kind: ClusterRole
  name: wiz-app-clusteradmin-role
  apiGroup: rbac.authorization.k8s.io
