apiVersion: v1
kind: Service
metadata:
  name: wizapp-lbservice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wiz-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
