apiVersion: v1
kind: Service
metadata:
  name: blogservice
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
