apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizapp
  template:
    metadata:
      labels:
        app: wizapp
    spec:
      containers:
      - name: wiz
        image: 789350153589.dkr.ecr.us-east-1.amazonaws.com/woonsworld:latest
        ports:
        - containerPort: 8080
